# Server Port
server.port=8081

# Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/pjsoft_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Root123

# Hibernate (Tells Java to build the tables!)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# File Upload Limits
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB